### ISSUE TITLE
BUG: network netplan. Не переносится параметр gateway4 при конфигурации моста с главным портом

### ISSUE THREAD

**Issue by VladimirTrue** [Aerodisk/openvair#118]
## Описание
При использовании netplan: После перезагрузки не работал, было связано с тем, что айпи был настроен статично, без dhcp, через параметр gateway4. В ходе анализа было обнаружено, что если маршрут настроен через параметр routes, то всё переносится корректно, а если через gateway4, то он просто не переносится в конфигурацию моста. Ниже пример конфигурации с routes и gateway(закомментирован)
```yaml
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp1s0:
      dhcp4: no
      addresses:
        - 192.168.122.50/24
      nameservers:
        addresses:
          - 192.168.122.1
      routes:
        - to: default
          via: 192.168.122.1
#      gateway4: 192.168.122.1

```

Нужно гарантировать перенос параметра `gateway4` в мост при статичной конфигурации netplan без dhcp

## Критерии приемки
1. Параметр `gateway4` главного порта корректно переносится в конфигурацию моста
2. Интернет соединение работает корректно
3. После перезагрузки машины соединение сохраняется
